"""
Initial Data Exploration — Step 1.3
====================================
Loads all datasets from data/raw/, runs comprehensive checks,
and saves a summary to docs/data_overview.txt.
"""

import os
import sys
import io
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(__file__))
RAW_DIR = os.path.join(BASE_DIR, "data", "raw")
DOCS_DIR = os.path.join(BASE_DIR, "docs")


def explore_dataframe(name, df, buf):
    """Run standard exploration checks on a DataFrame and write to buffer."""
    sep = "=" * 75
    buf.write(f"\n{sep}\n")
    buf.write(f"  TABLE: {name}\n")
    buf.write(f"{sep}\n\n")

    # Shape
    buf.write(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns\n\n")

    # Info (data types & null counts)
    buf.write("--- Data Types & Null Counts (.info()) ---\n")
    info_buf = io.StringIO()
    df.info(buf=info_buf)
    buf.write(info_buf.getvalue())
    buf.write("\n")

    # Describe (summary statistics)
    buf.write("--- Summary Statistics (.describe()) ---\n")
    buf.write(df.describe(include="all").to_string())
    buf.write("\n\n")

    # First 10 rows
    buf.write("--- First 10 Rows ---\n")
    buf.write(df.head(10).to_string())
    buf.write("\n\n")

    return df


def main():
    os.makedirs(DOCS_DIR, exist_ok=True)
    buf = io.StringIO()

    sep_line = "=" * 75
    header = (
        f"{sep_line}\n"
        f"  HOSPITAL ER WAIT TIME ANALYSIS — DATA OVERVIEW\n"
        f"  Generated by: scripts/explore_data.py\n"
        f"{sep_line}\n"
    )
    buf.write(header)

    # ── 1. Load datasets ──────────────────────────────────────────────────
    datasets = {}
    csv_files = sorted([f for f in os.listdir(RAW_DIR) if f.endswith(".csv")])

    if not csv_files:
        print("ERROR: No CSV files found in data/raw/")
        sys.exit(1)

    for fname in csv_files:
        path = os.path.join(RAW_DIR, fname)
        df = pd.read_csv(path)
        datasets[fname] = df
        print(f"Loaded {fname}: {df.shape[0]:,} rows × {df.shape[1]} cols")

    # ── 2. Explore each table ─────────────────────────────────────────────
    for name, df in datasets.items():
        explore_dataframe(name, df, buf)

    # ── 3. Synthetic visits — deeper dive ─────────────────────────────────
    visits_key = "er_synthetic_patient_visits.csv"
    if visits_key in datasets:
        df = datasets[visits_key]
        sep = "=" * 75
        buf.write(f"\n{sep}\n")
        buf.write(f"  DEEPER DIVE: {visits_key}\n")
        buf.write(f"{sep}\n\n")

        # Date range
        buf.write("--- Date Range ---\n")
        buf.write(f"  Earliest visit: {df['arrival_date'].min()}\n")
        buf.write(f"  Latest visit:   {df['arrival_date'].max()}\n\n")

        # Unique patients vs total visits
        buf.write("--- Unique Patients vs Total Visits ---\n")
        buf.write(f"  Total visits:     {len(df):,}\n")
        buf.write(f"  Unique patients:  {df['patient_id'].nunique():,}\n")
        avg_visits = len(df) / df['patient_id'].nunique()
        buf.write(f"  Avg visits/patient: {avg_visits:.2f}\n\n")

        # ESI level distribution
        buf.write("--- ESI Level Distribution ---\n")
        esi_counts = df["esi_level"].value_counts().sort_index()
        for esi, count in esi_counts.items():
            pct = count / len(df) * 100
            bar = "█" * int(pct)
            buf.write(f"  ESI {esi}: {count:>6,}  ({pct:5.1f}%)  {bar}\n")
        buf.write("\n")

        # Disposition distribution
        buf.write("--- Disposition Distribution ---\n")
        for disp, count in df["disposition"].value_counts().items():
            pct = count / len(df) * 100
            buf.write(f"  {disp:<15s}: {count:>6,}  ({pct:5.1f}%)\n")
        buf.write("\n")

        # Wait time stats by ESI
        buf.write("--- Wait Time (minutes) by ESI Level ---\n")
        wait_stats = df.groupby("esi_level")["wait_time_minutes"].agg(
            ["count", "mean", "median", "std", "min", "max"]
        )
        wait_stats.columns = ["Count", "Mean", "Median", "Std", "Min", "Max"]
        buf.write(wait_stats.to_string())
        buf.write("\n\n")

        # Total LOS stats by ESI
        buf.write("--- Total Length of Stay (minutes) by ESI Level ---\n")
        los_stats = df.groupby("esi_level")["total_los_minutes"].agg(
            ["count", "mean", "median", "std", "min", "max"]
        )
        los_stats.columns = ["Count", "Mean", "Median", "Std", "Min", "Max"]
        buf.write(los_stats.to_string())
        buf.write("\n\n")

        # Arrival patterns
        buf.write("--- Arrival Volume by Hour of Day ---\n")
        hour_counts = df["arrival_hour"].value_counts().sort_index()
        for hour, count in hour_counts.items():
            pct = count / len(df) * 100
            bar = "█" * int(pct * 2)
            buf.write(f"  {hour:02d}:00  {count:>5,}  ({pct:4.1f}%)  {bar}\n")
        buf.write("\n")

        buf.write("--- Arrival Volume by Day of Week ---\n")
        dow_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        dow_counts = df["arrival_day_of_week"].value_counts().reindex(dow_order)
        for day, count in dow_counts.items():
            pct = count / len(df) * 100
            buf.write(f"  {day:<12s}: {count:>6,}  ({pct:5.1f}%)\n")
        buf.write("\n")

        # Chief complaint frequency
        buf.write("--- Top 10 Chief Complaints ---\n")
        for complaint, count in df["chief_complaint"].value_counts().head(10).items():
            pct = count / len(df) * 100
            buf.write(f"  {complaint:<30s}: {count:>5,}  ({pct:4.1f}%)\n")
        buf.write("\n")

        # Demographics
        buf.write("--- Gender Distribution ---\n")
        for val, count in df["gender"].value_counts().items():
            pct = count / len(df) * 100
            buf.write(f"  {val:<15s}: {count:>6,}  ({pct:5.1f}%)\n")
        buf.write("\n")

        buf.write("--- Insurance Type Distribution ---\n")
        for val, count in df["insurance_type"].value_counts().items():
            pct = count / len(df) * 100
            buf.write(f"  {val:<15s}: {count:>6,}  ({pct:5.1f}%)\n")
        buf.write("\n")

        # Null check summary
        buf.write("--- Null Value Check ---\n")
        null_counts = df.isnull().sum()
        if null_counts.sum() == 0:
            buf.write("  ✓ No null values found in any column.\n")
        else:
            for col in null_counts[null_counts > 0].index:
                buf.write(f"  {col}: {null_counts[col]:,} nulls\n")
        buf.write("\n")

        # Vitals ranges
        buf.write("--- Vital Signs Ranges ---\n")
        vital_cols = ["heart_rate", "systolic_bp", "diastolic_bp",
                      "respiratory_rate", "spo2", "temperature_f", "pain_scale"]
        for col in vital_cols:
            buf.write(f"  {col:<20s}: "
                      f"min={df[col].min():.1f}, "
                      f"median={df[col].median():.1f}, "
                      f"max={df[col].max():.1f}\n")
        buf.write("\n")

    # ── 4. Save ───────────────────────────────────────────────────────────
    output_path = os.path.join(DOCS_DIR, "data_overview.txt")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(buf.getvalue())

    print(f"\n✅ Data overview saved → {output_path}")
    print(f"   ({len(buf.getvalue()):,} characters)")


if __name__ == "__main__":
    main()
